name: jira ticket validation
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
   contents: read
   
jobs:
  call-jira-label-pipeline:
    uses: MorningBlossom/ci-cd/.github/workflows/jira-validation.yml@main
    secrets: inherit
    with:
        jira-key: 'SP'